# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='booooooook',
        ),
    ]
