# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_bookstore', '0002_auto_20190717_0757'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='my_bookstore_book',
        ),
    ]
