# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='姓名')),
                ('upwd', models.CharField(max_length=100, verbose_name='密码')),
                ('uemail', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
            ],
        ),
    ]
