# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-15 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xiaojian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='jian', max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(default=25, verbose_name='年龄')),
            ],
        ),
    ]
