# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-16 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, null=True, verbose_name='书名')),
                ('pub_host', models.CharField(default='清华大学出版社', max_length=50, null=True, verbose_name='出版社')),
                ('pub_time', models.DateField(auto_now_add=True, verbose_name='出版时间')),
            ],
        ),
    ]
