# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-16 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_time',
            field=models.DateField(default='2017-12-12', verbose_name='出版时间'),
        ),
    ]
