# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-16 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20190716_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='emill',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='作者'),
        ),
    ]
