# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名字')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('mod_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.User'),
        ),
    ]
